

export const FETCH_ALBUMS_LIST_REQUEST = 'FETCH_ALBUMS_LIST_REQUEST';
export const FETCH_ALBUMS_LIST_SUCCESS = 'FETCH_ALBUMS_LIST_SUCCESS'
export const FETCH_ALBUMS_LIST_FAILURE = 'FETCH_ALBUMS_LIST_FAILURE'
